name: country_code_picker
description: Country code picker module
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.0

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/flags/